language: rust

rust:
  - 1.32.0
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
        - cargo build --verbose
        - cargo test --verbose

script:
  - cargo build --verbose
  - cargo test --verbose
