[package]
name = "petal-neighbors"
version = "0.1.0"
authors = [
    "Min Kim <msk@dolbo.net>",
    "Min Shao <min.shao1988@gmail.com>"
]
edition = "2018"

[dependencies]
ndarray = "0.13"

[dev-dependencies]
rand = "0.7"
